@echo off
echo Setting remote...
git remote set-url origin https://github.com/limchang/jina-hangul
echo Adding files...
git add .
echo Committing...
git commit -m "🎉 Update: Complete Fairytale UI (SVG icons, smooth tracing)"
echo Pushing...
git push origin main
if %errorlevel% neq 0 git push origin master
echo Done.
