@echo off
echo Copying images...
copy "C:\Users\Administrator\.gemini\antigravity\brain\ad00b39c-4764-424e-8fa7-71b400c636bb\*.png" .
echo Adding files to git...
git add .
echo Committing...
git commit -m "Premium Hangul study UI update with assets"
echo Pushing...
git push origin main
if %errorlevel% neq 0 git push origin master
echo Done.
